title: Yoann Dupont
description: ​&quot;Associate professor&quot; in NLP
description_fr: Maître de conférences en Sciences du Langage
contact: ​&lt;firstname&gt; . &lt;lastname&gt; @ sorbonne-nouvelle . fr
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
github.is_project_page: true
github.repository_url: https://github.com/YoannDupont/YoannDupont.github.io
portrait: files/images/portrait.png
